### PR TITLE
Incorporate memlock rlimit check into SEV-readiness

### PR DESCRIPTION
**Pull request by connorkuehl**
Closes: #14 

Looks like this:

```console
$ cargo run info
[..]
 ✔ MEMLOCK rlimit allows for: ~1638 keeps (soft limit = 8589934592 bytes, hard limit = 8589934592 bytes)
```

Or on a machine that can't meet this requirement:

```console
$ cargo run info
[..]
 ✗ MEMLOCK rlimit allows for: 0 keeps (soft limit = 65536 bytes, hard limit = 65536 bytes)

The MEMLOCK rlimit must be large enough to accommodate the Enarx shim, wasmldr, and the memory pressure requirements of the target workloads across all deployed SEV keeps.
```

Signed-off-by: Connor Kuehl <ckuehl@redhat.com>

### CODE REVIEW

**Comment by haraldh** [comment]
Does that mean, it will automatically silently fallback to plain `kvm`, if the memlock rlimit is too low?

I am thinking of the testsuite.

**Comment by connorkuehl** [comment]
> Does that mean, it will automatically silently fallback to plain `kvm`, if the memlock rlimit is too low?
> 
> I am thinking of the testsuite.

For CI, no, because the CI sets the `ENARX_BACKEND` variable which will fail if the backend checks fail.

For a regular developer workflow running `cargo test` on their own machine, yes, this will silently switch to `kvm` if the developer doesn't set `ENARX_BACKEND`.

**Comment by connorkuehl** [comment]
> The tool should probably be verbose about running a non TEE backend.

Emitting this information on stdout/stderr will spuriously break our integration tests for test runs on a non-TEE backend.

**Comment by haraldh** [comment]
Isn't the backend specified and there is no fallback then?

**Comment by connorkuehl** [comment]
> Isn't the backend specified and there is no fallback then?

Not if you're just running `cargo test` without `ENARX_BACKEND` set. This is pretty common in my workflow.

Silently switching to a supported backend when `ENARX_BACKEND` is not set is how this has always behaved; it isn't introduced by this PR.

**Review by haraldh — APPROVED** [review]

**Review by lkatalin — APPROVED** [review]
This makes sense!

**Pull request merged**
