### PR TITLE
rework of shim-sev: handle multiple return values for syscalls

### PR DESCRIPTION
**Pull request by haraldh**
Revert the previous patch and introduce a much simpler one.

shim-sev: handle multiple return values for syscalls

`rdx` is sometimes used as a secondary return value.

This patch lets `syscall_rust` return a double u64 struct instead of u64,
which will use `rax` for the first 64 bits and `rdx` for the last 64 bit.

Because `rdx` is not marked as `clobber` for the musl syscall macro,
the original value has to be returned, if `rdx` is unused as a return
value.

This patch also adds a dummy path for the enarx syscalls, which can make
use of the second return value.

Signed-off-by: Harald Hoyer <harald@redhat.com>

### CODE REVIEW

**Comment by haraldh** [comment]
Best to review commit by commit.

**Review by lkatalin — APPROVED** [review]
Seems like a good solution to me.

**Review by npmccallum — COMMENTED** [review]
@haraldh It looks like you're inventing new types (`X8664DoubleReturn`), but we already have similar types in `sallyport`. Why not use those?

**Comment by haraldh** [comment]
> @haraldh It looks like you're inventing new types (`X8664DoubleReturn`), but we already have similar types in `sallyport`. Why not use those?

@npmccallum I don't see any FFI-safe type with two u64/usize struct members in `sallyport`

**Comment by npmccallum** [comment]
> @npmccallum I don't see any FFI-safe type with two u64/usize struct members in `sallyport`

https://github.com/enarx/enarx-keepldr/blob/master/src/sallyport/mod.rs#L92

**Review by npmccallum — APPROVED** [review]

**Pull request merged**
