### PR TITLE
Test that clippy::all is present in all crates

### PR DESCRIPTION
**Pull request by mbestavros**
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

### CODE REVIEW

**Comment by npmccallum** [comment]
@mbestavros I'm not quite sure why the lints aren't running...

**Comment by connorkuehl** [comment]
It's been my experience that disappearing checks are a symptom of a syntax error in the yaml file; though that is often times accompanied by a github notification saying so

**Comment by mbestavros** [comment]
@connorkuehl It was indeed that... an indentation error, of all things. ¯\_(ツ)_/¯

**Review by haraldh — APPROVED** [review]

**Review by npmccallum — CHANGES_REQUESTED** [review]
Thinking about this test a bit more, I suspect it is only useful in a multi-crate repo situation. I suspect it is probably just easier to create a new repo template that has all the stuff we want in it.

**Comment by mbestavros** [comment]
Having discussed this a bit more with @npmccallum on our daily standup, I agree a template is simpler. Closing this test for now.

**Pull request closed without merging**
